### ISSUE TITLE
The speed gradually slows down！

### ISSUE THREAD

**Issue by CuberrChen** [PRBonn/puma#7]
Hello, this job looks very good. So I ran it successfully with a few minor modifications to fit my environment, but it seems that the speed of processing a frame of point cloud is getting slower. Is the reason that every frame will match all the previous meshs?

**Comment by nachovizzo** [comment]
Hello, sorry for the late response.

The first `n` frames the system will rely on "frame-to-frame" ICP, since no map is available. From that point on, the system will use the previously built mesh to estimate the pose of the vehicle. Due to the long runtime of the meshing algorithm, this process is particularly slow, as highlighted in the publication: 
![image](https://user-images.githubusercontent.com/21349875/126128993-d1da9059-a4b8-4beb-b965-b5dfa50af014.png)

One option would be to replace the meshing algorithm for one based on TSDF but for LiDAR data, based on my experience this never turns to work out properly....

**Comment by nachovizzo** [comment]
I'm re-opening this issue because we are about to release a reconstruction pipeline that solves this same issue, stay tunned.

**Comment by nachovizzo** [comment]
@CuberrChen here is the mentioned pipeline: https://github.com/PRBonn/vdbfusion
